version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - simplebank-network
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"
    networks:
      - simplebank-network 
  api: 
      build: 
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "8080:8080"
        - "9090:9090"
      environment:
        GIN_MODE: debug
        DB_SOURCE: postgresql://user:password@postgres12:5432/simple_bank?sslmode=disable
        REDIS_ADDRESS: redis:6379
      depends_on:
        - postgres
        - redis
      networks:
        - simplebank-network 
      entrypoint: ["/app/wait-for.sh", "postgres12:5432", "--", "/app/main"]

networks:
  simplebank-network:
    external: true
