name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: guncv
          POSTGRES_PASSWORD: 17554Guncv_26042003
          POSTGRES_DB: simplebank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10  # Increased retries for stability

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # ✅ Updated to Go 1.23 for compatibility

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          which migrate  # Verify installation

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Generate SQLC Code # ✅ Generate SQL code before migration
        run: make sqlc

      - name: Run Migrations
        run: make migrate-up

      - name: Run Tests
        run: make test
